language: python
cache: pip
sudo: false
python:
  - 3.4
addons:
  apt:
    packages:
    - glpk-utils
  addons:
    postgresql: "9.4"
services:
  - postgresql
env:
  - SETTINGS=./config/travis.cfg
install:
  - make update
before_script:
  - psql -c 'create database emf-site-test;' -U postgres
script:
  - make test
