language: python
cache:
  directories:
    - $HOME/.cache/pip
sudo: false
python:
  - 2.7
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y glpk-utils
install:
  - make update
script:
  - make test
