version: "3.7"
services:
  app:
    build:
      context: "./"
    networks:
      - emfweb
    depends_on:
      - postgres
    volumes:
      - .:/app
      - ./var/vat_invoices:/vat_invoices
    ports:
      - "5000:5000"
    environment:
      SETTINGS_FILE: ./config/development.cfg

  postgres:
    image: 'mdillon/postgis:10'
    networks:
      - emfweb

networks:
  emfweb:
