version: "3.7"
services:
  app:
    image: "emfcamp/website:latest"
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - /etc/emf-site.cfg:/app/config/production.cfg
      - /var/lib/emf_vat_invoices:/vat_invoices
    environment:
      SETTINGS_FILE: ./config/production.cfg
      PROMETHEUS_MULTIPROC_DIR: /var/prometheus

  postgres:
    volumes: 
      - /var/lib/emfweb-postgres:/var/lib/postgresql/data
