version: "3.7"
services:
  app:
    build:
      context: "./"
      dockerfile: Dockerfile.prod
    volumes:
      - /etc/emf-site.cfg:/app/config/production.cfg
    environment:
      SETTINGS_FILE: ./config/production.cfg
      PROMETHEUS_MULTIPROC_DIR: /var/prometheus

  postgres:
    volumes: 
      - /var/lib/emfweb-postgres:/var/lib/postgresql/data
