version: "3.7"
services:
  app:
    build:
      context: "./"
      dockerfile: Dockerfile.prod
    environment:
      SETTINGS_FILE: ./config/development.cfg
      PROMETHEUS_MULTIPROC_DIR: /var/prometheus

  postgres:
    volumes: 
      - /var/lib/emfweb-postgres:/var/lib/postgresql/data
